"""add image_url to jobs table

Revision ID: 100d88c51a0a
Revises: 63ef761a3e4a
Create Date: 2025-10-27 13:14:32.352493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '100d88c51a0a'
down_revision: Union[str, Sequence[str], None] = '63ef761a3e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('image_url', sa.String(512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'image_url')
    # ### end Alembic commands ###
