"""fresh_schema

Revision ID: 1bbe7c99bfca
Revises: 
Create Date: 2025-10-01 21:39:11.286007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbe7c99bfca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_questions',
    sa.Column('id_list_question', sa.Integer(), nullable=False),
    sa.Column('list_title', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_list_question')
    )
    op.create_index(op.f('ix_list_questions_id_list_question'), 'list_questions', ['id_list_question'], unique=False)
    op.create_table('questions',
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('question_title', sa.Text(), nullable=False),
    sa.Column('url_video', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_question')
    )
    op.create_index(op.f('ix_questions_id_question'), 'questions', ['id_question'], unique=False)
    op.create_table('list_question_items',
    sa.Column('id_lqi', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list_questions.id_list_question'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id_question'], ),
    sa.PrimaryKeyConstraint('id_lqi')
    )
    op.create_index(op.f('ix_list_question_items_id_lqi'), 'list_question_items', ['id_lqi'], unique=False)
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('assigned_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_list_id'], ['list_questions.id_list_question'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('id_list_questions', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['id_list_questions'], ['list_questions.id_list_question'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id_question'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_list_question_items_id_lqi'), table_name='list_question_items')
    op.drop_table('list_question_items')
    op.drop_index(op.f('ix_questions_id_question'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_list_questions_id_list_question'), table_name='list_questions')
    op.drop_table('list_questions')
    # ### end Alembic commands ###
