"""add minutes to listquestions

Revision ID: 4acd5ad8fce2
Revises: 1bbe7c99bfca
Create Date: 2025-10-24 10:18:49.510586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4acd5ad8fce2'
down_revision: Union[str, Sequence[str], None] = '1bbe7c99bfca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_questions', sa.Column('minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list_questions', 'minutes')
    # ### end Alembic commands ###
