"""add transcript to answer table

Revision ID: 932214f45a1c
Revises: 4acd5ad8fce2
Create Date: 2025-10-25 09:03:27.586517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932214f45a1c'
down_revision: Union[str, Sequence[str], None] = '4acd5ad8fce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'transcript')
    # ### end Alembic commands ###
